- name: 1Password
  identifier:
    kind: exe
    id: 1Password.exe
  float_identifiers:
  - kind: exe
    id: 1Password.exe
- name: Adobe Creative Cloud
  identifier:
    kind: class
    id: CreativeCloudDesktopWindowClass
  options:
  - tray_and_multi_window
- name: Adobe Photoshop
  identifier:
    kind: class
    id: Photoshop
  options:
  - border_overflow
- name: ArmCord
  identifier:
    kind: exe
    id: ArmCord.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: AutoHotkey
  identifier:
    kind: exe
    id: AutoHotkeyU64.exe
  options:
  - tray_and_multi_window
  float_identifiers:
  - kind: title
    id: Window Spy
- name: Beeper
  identifier:
    kind: exe
    id: Beeper.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Bitwarden
  identifier:
    kind: exe
    id: Bitwarden.exe
  options:
  - tray_and_multi_window
- name: Bloxstrap
  identifier:
    kind: exe
    id: Bloxstrap.exe
  float_identifiers:
  - kind: exe
    id: Bloxstrap.exe
- name: Calculator
  identifier:
    kind: title
    id: Calculator
  float_identifiers:
  - kind: title
    id: Calculator
- name: Credential Manager UI Host
  identifier:
    kind: exe
    id: CredentialUIBroker.exe
  float_identifiers:
  - kind: exe
    id: CredentialUIBroker.exe
    comment: Targets the Windows popup prompting you for a PIN instead of a password on 1Password etc.
- name: Cron
  identifier:
    kind: exe
    id: Cron.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Delphi applications
  identifier:
    kind: class
    id: TApplication
  float_identifiers:
  - kind: class
    id: TApplication
    comment: Target hidden window spawned by Delphi applications
  - kind: class
    id: TWizardForm
    comment: Target Inno Setup installers
- name: Discord
  identifier:
    kind: exe
    id: Discord.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: DiscordCanary
  identifier:
    kind: exe
    id: DiscordCanary.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: DiscordDevelopment
  identifier:
    kind: exe
    id: DiscordDevelopment.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: DiscordPTB
  identifier:
    kind: exe
    id: DiscordPTB.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: ElectronMail
  identifier:
    kind: exe
    id: ElectronMail.exe
  options:
  - tray_and_multi_window
- name: Element
  identifier:
    kind: exe
    id: Element.exe
  options:
  - tray_and_multi_window
- name: ElevenClock
  identifier:
    kind: exe
    id: ElevenClock.exe
  options:
  - tray_and_multi_window
- name: Elgato Camera Hub
  identifier:
    kind: exe
    id: Camera Hub.exe
  float_identifiers:
  - kind: exe
    id: Camera Hub.exe
- name: Elgato Control Center
  identifier:
    kind: exe
    id: ControlCenter.exe
  float_identifiers:
  - kind: exe
    id: ControlCenter.exe
- name: Elgato Wave Link
  identifier:
    kind: exe
    id: WaveLink.exe
  float_identifiers:
  - kind: exe
    id: WaveLink.exe
- name: Epic Games Launcher
  identifier:
    kind: exe
    id: EpicGamesLauncher.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Flow Launcher
  identifier:
    kind: exe
    id: Flow.Launcher.exe
  options:
  - border_overflow
- name: GOG Galaxy
  identifier:
    kind: exe
    id: GalaxyClient.exe
  options:
  - border_overflow
  - force
  - tray_and_multi_window
  float_identifiers:
  - kind: class
    id: Chrome_RenderWidgetHostHWND
    comment: Targets a hidden window spawned by GOG Galaxy
- name: GoPro Webcam
  identifier:
    kind: class
    id: GoPro Webcam
  options:
  - tray_and_multi_window
- name: Godot Manager
  identifier:
    kind: exe
    id: GodotManager.exe
  options:
  - border_overflow
  - force
  - object_name_change
- name: Google Chrome
  identifier:
    kind: exe
    id: chrome.exe
  options:
  - tray_and_multi_window
- name: Google Drive
  identifier:
    kind: exe
    id: GoogleDriveFS.exe
  options:
  - tray_and_multi_window
- name: Houdoku
  identifier:
    kind: exe
    id: Houdoku.exe
  options:
  - border_overflow
- name: IntelliJ IDEA
  identifier:
    kind: exe
    id: idea64.exe
  options:
  - object_name_change
  - tray_and_multi_window
  float_identifiers:
  - kind: class
    id: SunAwtDialog
    comment: Targets JetBrains IDE popups and floating windows
- name: Itch.io
  identifier:
    kind: exe
    id: itch.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Kleopatra
  identifier:
    kind: exe
    id: kleopatra.exe
  options:
  - tray_and_multi_window
- name: Kotatogram
  identifier:
    kind: exe
    id: Kotatogram.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Logi Bolt
  identifier:
    kind: exe
    id: LogiBolt.exe
  float_identifiers:
  - kind: exe
    id: LogiBolt.exe
- name: LogiTune
  identifier:
    kind: exe
    id: LogiTune.exe
  options:
  - tray_and_multi_window
  float_identifiers:
  - kind: exe
    id: LogiTune.exe
- name: Logitech G HUB
  identifier:
    kind: exe
    id: lghub.exe
  options:
  - tray_and_multi_window
  - border_overflow
- name: Logitech Options
  identifier:
    kind: exe
    id: LogiOptionsUI.exe
  float_identifiers:
  - kind: exe
    id: LogiOptionsUI.exe
- name: Mailspring
  identifier:
    kind: exe
    id: mailspring.exe
  options:
  - tray_and_multi_window
- name: ManyCam
  identifier:
    kind: exe
    id: ManyCam.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Mica For Everyone
  identifier:
    kind: exe
    id: MicaForEveryone.exe
- name: Microsoft Excel
  identifier:
    kind: exe
    id: EXCEL.EXE
  options:
  - border_overflow
  - layered
  float_identifiers:
  - kind: class
    id: _WwB
    comment: Targets a hidden window spawned by Microsoft Office applications
- name: Microsoft Outlook
  identifier:
    kind: exe
    id: OUTLOOK.EXE
  options:
  - border_overflow
  - layered
  - tray_and_multi_window
  float_identifiers:
  - kind: class
    id: _WwB
    comment: Targets a hidden window spawned by Microsoft Office applications
- name: Microsoft PowerPoint
  identifier:
    kind: exe
    id: POWERPNT.EXE
  options:
  - border_overflow
  - layered
  float_identifiers:
  - kind: class
    id: _WwB
    comment: Targets a hidden window spawned by Microsoft Office applications
- name: Microsoft Teams
  identifier:
    kind: exe
    id: Teams.exe
  options:
  - border_overflow
  float_identifiers:
  - kind: title
    id: Microsoft Teams Notification
    comment: Target Teams pop-up notification windows
  - kind: title
    id: Microsoft Teams Call
    comment: Target Teams call in progress windows
- name: Microsoft Word
  identifier:
    kind: exe
    id: WINWORD.EXE
  options:
  - border_overflow
  - layered
  float_identifiers:
  - kind: class
    id: _WwB
    comment: Targets a hidden window spawned by Microsoft Office applications
- name: Modern Flyouts
  identifier:
    kind: exe
    id: ModernFlyoutsHost.exe
  options:
  - tray_and_multi_window
- name: Mozilla Firefox
  identifier:
    kind: exe
    id: firefox.exe
  options:
  - object_name_change
  - tray_and_multi_window
  float_identifiers:
  - kind: class
    id: MozillaTaskbarPreviewClass
    comment: Targets invisible windows spawned by Firefox to show tab previews in the taskbar
- name: NVIDIA GeForce Experience
  identifier:
    kind: exe
    id: NVIDIA GeForce Experience.exe
  options:
  - border_overflow
- name: NiceHash Miner
  identifier:
    kind: exe
    id: nhm_app.exe
  options:
  - border_overflow
  - force
- name: NohBoard
  identifier:
    kind: exe
    id: NohBoard.exe
  float_identifiers:
  - kind: exe
    id: NohBoard.exe
- name: Notion Enhanced
  identifier:
    kind: exe
    id: Notion Enhanced.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: OBS Studio (32-bit)
  identifier:
    kind: exe
    id: obs32.exe
  options:
  - tray_and_multi_window
- name: OBS Studio (64-bit)
  identifier:
    kind: exe
    id: obs64.exe
  options:
  - tray_and_multi_window
- name: ONLYOFFICE Editors
  identifier:
    kind: class
    id: DocEditorsWindowClass
  options:
  - border_overflow
  - tray_and_multi_window
- name: Obsidian
  identifier:
    kind: exe
    id: Obsidian.exe
  options:
  - border_overflow
  - force
- name: OpenRGB
  identifier:
    kind: exe
    id: OpenRGB.exe
  options:
  - tray_and_multi_window
- name: Paradox Launcher
  identifier:
    kind: exe
    id: Paradox Launcher.exe
  float_identifiers:
  - kind: exe
    id: Paradox Launcher.exe
- name: PowerToys
  identifier:
    kind: exe
    id: PowerToys.exe
  float_identifiers:
  - kind: exe
    id: PowerToys.ColorPickerUI.exe
    comment: Target color picker dialog
  - kind: exe
    id: PowerToys.ImageResizer.exe
    comment: Target image resizer dialog
- name: Process Hacker
  identifier:
    kind: exe
    id: ProcessHacker.exe
  options:
  - tray_and_multi_window
  float_identifiers:
  - kind: exe
    id: ProcessHacker.exe
- name: ProtonVPN
  identifier:
    kind: exe
    id: ProtonVPN.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: PyCharm
  identifier:
    kind: exe
    id: pycharm64.exe
  options:
  - object_name_change
  - tray_and_multi_window
  float_identifiers:
  - kind: class
    id: SunAwtDialog
    comment: Targets JetBrains IDE popups and detached windows
- name: QuickLook
  identifier:
    kind: exe
    id: QuickLook.exe
  float_identifiers:
  - kind: exe
    id: QuickLook.exe
- name: RepoZ
  identifier:
    kind: exe
    id: RepoZ.exe
  float_identifiers:
  - kind: exe
    id: RepoZ.exe
- name: Roblox FPS Unlocker
  identifier:
    kind: exe
    id: rbxfpsunlocker.exe
  options:
  - tray_and_multi_window
- name: RoundedTB
  identifier:
    kind: exe
    id: RoundedTB.exe
  float_identifiers:
  - kind: exe
    id: RoundedTB.exe
- name: RoundedTB
  identifier:
    kind: exe
    id: RoundedTB.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: ShareX
  identifier:
    kind: exe
    id: ShareX.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Signal
  identifier:
    kind: exe
    id: signal.exe
  options:
  - tray_and_multi_window
- name: SiriKali
  identifier:
    kind: exe
    id: sirikali.exe
  options:
  - tray_and_multi_window
- name: Slack
  identifier:
    kind: exe
    id: Slack.exe
  options:
  - border_overflow
  - force
  - tray_and_multi_window
  float_identifiers:
  - kind: class
    id: Chrome_RenderWidgetHostHWND
    comment: Targets a hidden window spawned by Slack
- name: Slack
  identifier:
    kind: exe
    id: slack.exe
  options:
  - border_overflow
  - force
  - tray_and_multi_window
  float_identifiers:
  - kind: class
    id: Chrome_RenderWidgetHostHWND
    comment: Targets a hidden window spawned by Slack
- name: Smart Install Maker
  identifier:
    kind: exe
    id: SIM.exe
  float_identifiers:
  - kind: class
    id: obj_App
    comment: Target hidden window spawned by installer
  - kind: class
    id: obj_Form
    comment: Target installer
- name: SoulseekQt
  identifier:
    kind: exe
    id: SoulseekQt.exe
  options:
  - tray_and_multi_window
- name: Spotify
  identifier:
    kind: exe
    id: Spotify.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Steam
  identifier:
    kind: class
    id: vguiPopupWindow
  options:
  - border_overflow
- name: System Informer
  identifier:
    kind: exe
    id: SystemInformer.exe
  options:
  - tray_and_multi_window
  float_identifiers:
  - kind: exe
    id: SystemInformer.exe
- name: SystemSettings
  identifier:
    kind: exe
    id: SystemSettings.exe
  float_identifiers:
  - kind: class
    id: Shell_Dialog
- name: Task Manager
  identifier:
    kind: exe
    id: Taskmgr.exe
  float_identifiers:
  - kind: class
    id: TaskManagerWindow
- name: Telegram
  identifier:
    kind: exe
    id: Telegram.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: TouchCursor
  identifier:
    kind: exe
    id: tcconfig.exe
  options:
  - tray_and_multi_window
  float_identifiers:
  - kind: exe
    id: tcconfig.exe
- name: TranslucentTB
  identifier:
    kind: exe
    id: TranslucentTB.exe
  float_identifiers:
  - kind: exe
    id: TranslucentTB.exe
- name: TranslucentTB
  identifier:
    kind: exe
    id: TranslucentTB.exe
  options:
  - tray_and_multi_window
- name: Unreal Editor
  identifier:
    kind: exe
    id: UnrealEditor.exe
  options:
  - border_overflow
  - tray_and_multi_window
- name: Visual Studio
  identifier:
    kind: exe
    id: devenv.exe
  options:
  - object_name_change
- name: Visual Studio Code
  identifier:
    kind: exe
    id: Code.exe
  options:
  - border_overflow
- name: WebTorrent Desktop
  identifier:
    kind: exe
    id: WebTorrent.exe
  options:
  - tray_and_multi_window
- name: Windows Console (conhost.exe)
  identifier:
    kind: class
    id: ConsoleWindowClass
  options:
  - force
- name: Windows Explorer
  identifier:
    kind: exe
    id: explorer.exe
  float_identifiers:
  - kind: class
    id: OperationStatusWindow
    comment: Targets copy/move operation windows
  - kind: title
    id: Control Panel
- name: Windows Installer
  identifier:
    kind: exe
    id: msiexec.exe
  float_identifiers:
  - kind: class
    id: MsiDialogCloseClass
    comment: Targets MSI Installers
- name: WingetUI
  identifier:
    kind: exe
    id: WingetUI.exe
  options:
  - tray_and_multi_window
- name: WingetUI
  identifier:
    kind: exe
    id: wingetui.exe
  options:
  - tray_and_multi_window
- name: Wox
  identifier:
    kind: exe
    id: Wox.exe
  float_identifiers:
  - kind: title
    id: Hotkey sink
    comment: Targets a hidden window spawned by Wox
- name: XAMPP Control Panel
  identifier:
    kind: exe
    id: xampp-control.exe
  options:
  - tray_and_multi_window
- name: Zoom
  identifier:
    kind: exe
    id: Zoom.exe
  float_identifiers:
  - kind: exe
    id: Zoom.exe
- name: mpv.net
  identifier:
    kind: exe
    id: mpvnet.exe
  options:
  - object_name_change
- name: paint.net
  identifier:
    kind: exe
    id: paintdotnet.exe
  float_identifiers:
  - kind: exe
    id: paintdotnet.exe
- name: pinentry
  identifier:
    kind: exe
    id: pinentry.exe
  float_identifiers:
  - kind: exe
    id: pinentry.exe
- name: qBittorrent
  identifier:
    kind: exe
    id: qbittorrent.exe
  options:
  - tray_and_multi_window
- name: ueli
  identifier:
    kind: exe
    id: ueli.exe
  options:
  - tray_and_multi_window
  float_identifiers:
  - kind: exe
    id: ueli.exe
